### ISSUE TITLE
General Question on Usage

### ISSUE THREAD

**Issue by protbiochem** [BenevolentAI/DeeplyTough#9]
I have just a general question about usage. I've been using the TOUGH-M1 dataset to compare a bunch of pockets. When I look at the results I get values ranging from 0 to -1. What would you say is generally the best number to use as a cutoff for saying two things have the same binding capabilities but without introducing too many false positives? I look at figure 2 with the ROC curve in the paper and it appears to me that at around 80% accuracy for true positives, and ~10% false negatives seems to be an ideal position. But that ROC curve doesn't give any cutoff values for what each point in the curve correlates to. I would greatly appreciate this type of information. Thanks

**Comment by mys007** [comment]
Hi. You're right, you can base yourself from a dataset you find conceptually similar to your problem (TOUGH-M1 or Vertex, likely), look at the ROC curve there and choose a TPR/FPR balance you want to have. You need to download all the data and run `toughm1_benchmark.py` or `vertex_benchmark.py`. This will produce a pickle file with results. There, 'tpr' and 'th_roc' fields contain the paired information you want to have (i.e. what threshold is needed for a specific TPR).



In order to get the particular threshold, you need to look a
